using System.ComponentModel;
using System.Windows.Forms;

namespace NSUNS4_Character_Manager
{
    partial class Tool_TrailEditor
    {
        private IContainer components = null;
        private Label chunkLabel;
        private Label chunkNameLabel;
        private Label chunkPathLabel;
        private TabPage managersTabPage;
        private TabPage resourcesTabPage;
        private TabPage positionsTabPage;
        private TabPage forceFieldsTabPage;
        private TabPage mapIdsTabPage;
        private TabPage nodesTabPage;
        private SplitContainer managersSplitContainer;
        private SplitContainer resourcesSplitContainer;
        private SplitContainer positionsSplitContainer;
        private SplitContainer forceFieldsSplitContainer;
        private SplitContainer mapIdsSplitContainer;
        private SplitContainer nodesSplitContainer;
        private SplitContainer nodeDetailsSplitContainer;
        private SplitContainer framesSplitContainer;
        private FlowLayoutPanel managersButtonsPanel;
        private FlowLayoutPanel resourcesButtonsPanel;
        private FlowLayoutPanel positionsButtonsPanel;
        private FlowLayoutPanel forceFieldsButtonsPanel;
        private FlowLayoutPanel mapIdsButtonsPanel;
        private FlowLayoutPanel nodesButtonsPanel;
        private FlowLayoutPanel framesButtonsPanel;
        private Button addManagerButton;
        private Button duplicateManagerButton;
        private Button deleteManagerButton;
        private Button addResourceButton;
        private Button duplicateResourceButton;
        private Button deleteResourceButton;
        private Button addPositionButton;
        private Button duplicatePositionButton;
        private Button deletePositionButton;
        private Button addForceFieldButton;
        private Button duplicateForceFieldButton;
        private Button deleteForceFieldButton;
        private Button addMapButton;
        private Button duplicateMapButton;
        private Button deleteMapButton;
        private Button addNodeButton;
        private Button duplicateNodeButton;
        private Button deleteNodeButton;
        private Button addFrameButton;
        private Button duplicateFrameButton;
        private Button deleteFrameButton;
        private Label nodeDetailsLabel;
        private Label frameDetailsLabel;

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (backend != null)
                {
                    backend.Dispose();
                    backend = null;
                }
                if (components != null)
                    components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new Container();
            this.menuStrip1 = new MenuStrip();
            this.fileToolStripMenuItem = new ToolStripMenuItem();
            this.openToolStripMenuItem = new ToolStripMenuItem();
            this.saveToolStripMenuItem = new ToolStripMenuItem();
            this.saveAsToolStripMenuItem = new ToolStripMenuItem();
            this.closeToolStripMenuItem = new ToolStripMenuItem();
            this.detailsPanel = new Panel();
            this.chunkLabel = new Label();
            this.chunkComboBox = new ComboBox();
            this.chunkNameLabel = new Label();
            this.chunkNameTextBox = new TextBox();
            this.chunkPathLabel = new Label();
            this.chunkPathTextBox = new TextBox();
            this.tabControl1 = new TabControl();
            this.managersTabPage = new TabPage();
            this.resourcesTabPage = new TabPage();
            this.positionsTabPage = new TabPage();
            this.forceFieldsTabPage = new TabPage();
            this.mapIdsTabPage = new TabPage();
            this.nodesTabPage = new TabPage();
            this.managersSplitContainer = new SplitContainer();
            this.resourcesSplitContainer = new SplitContainer();
            this.positionsSplitContainer = new SplitContainer();
            this.forceFieldsSplitContainer = new SplitContainer();
            this.mapIdsSplitContainer = new SplitContainer();
            this.nodesSplitContainer = new SplitContainer();
            this.nodeDetailsSplitContainer = new SplitContainer();
            this.framesSplitContainer = new SplitContainer();
            this.managersListBox = new ListBox();
            this.resourcesListBox = new ListBox();
            this.positionsListBox = new ListBox();
            this.forceFieldsListBox = new ListBox();
            this.mapIdsListBox = new ListBox();
            this.nodesListBox = new ListBox();
            this.framesListBox = new ListBox();
            this.managersPropertyGrid = new PropertyGrid();
            this.resourcesPropertyGrid = new PropertyGrid();
            this.positionsPropertyGrid = new PropertyGrid();
            this.forceFieldsPropertyGrid = new PropertyGrid();
            this.mapIdsPropertyGrid = new PropertyGrid();
            this.nodesPropertyGrid = new PropertyGrid();
            this.framesPropertyGrid = new PropertyGrid();
            this.managersButtonsPanel = new FlowLayoutPanel();
            this.resourcesButtonsPanel = new FlowLayoutPanel();
            this.positionsButtonsPanel = new FlowLayoutPanel();
            this.forceFieldsButtonsPanel = new FlowLayoutPanel();
            this.mapIdsButtonsPanel = new FlowLayoutPanel();
            this.nodesButtonsPanel = new FlowLayoutPanel();
            this.framesButtonsPanel = new FlowLayoutPanel();
            this.addManagerButton = new Button();
            this.duplicateManagerButton = new Button();
            this.deleteManagerButton = new Button();
            this.addResourceButton = new Button();
            this.duplicateResourceButton = new Button();
            this.deleteResourceButton = new Button();
            this.addPositionButton = new Button();
            this.duplicatePositionButton = new Button();
            this.deletePositionButton = new Button();
            this.addForceFieldButton = new Button();
            this.duplicateForceFieldButton = new Button();
            this.deleteForceFieldButton = new Button();
            this.addMapButton = new Button();
            this.duplicateMapButton = new Button();
            this.deleteMapButton = new Button();
            this.addNodeButton = new Button();
            this.duplicateNodeButton = new Button();
            this.deleteNodeButton = new Button();
            this.addFrameButton = new Button();
            this.duplicateFrameButton = new Button();
            this.deleteFrameButton = new Button();
            this.nodeDetailsLabel = new Label();
            this.frameDetailsLabel = new Label();
            this.menuStrip1.SuspendLayout();
            this.detailsPanel.SuspendLayout();
            this.tabControl1.SuspendLayout();
            this.managersTabPage.SuspendLayout();
            this.resourcesTabPage.SuspendLayout();
            this.positionsTabPage.SuspendLayout();
            this.forceFieldsTabPage.SuspendLayout();
            this.mapIdsTabPage.SuspendLayout();
            this.nodesTabPage.SuspendLayout();
            ((ISupportInitialize)(this.managersSplitContainer)).BeginInit();
            ((ISupportInitialize)(this.resourcesSplitContainer)).BeginInit();
            ((ISupportInitialize)(this.positionsSplitContainer)).BeginInit();
            ((ISupportInitialize)(this.forceFieldsSplitContainer)).BeginInit();
            ((ISupportInitialize)(this.mapIdsSplitContainer)).BeginInit();
            ((ISupportInitialize)(this.nodesSplitContainer)).BeginInit();
            ((ISupportInitialize)(this.nodeDetailsSplitContainer)).BeginInit();
            ((ISupportInitialize)(this.framesSplitContainer)).BeginInit();
            this.SuspendLayout();
            this.menuStrip1.Items.AddRange(new ToolStripItem[] { this.fileToolStripMenuItem });
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(1324, 24);
            this.fileToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[] { this.openToolStripMenuItem, this.saveToolStripMenuItem, this.saveAsToolStripMenuItem, this.closeToolStripMenuItem });
            this.fileToolStripMenuItem.Text = "File";
            this.openToolStripMenuItem.Text = "Open";
            this.openToolStripMenuItem.Click += new System.EventHandler(this.openToolStripMenuItem_Click);
            this.saveToolStripMenuItem.Text = "Save";
            this.saveToolStripMenuItem.Click += new System.EventHandler(this.saveToolStripMenuItem_Click);
            this.saveAsToolStripMenuItem.Text = "Save As...";
            this.saveAsToolStripMenuItem.Click += new System.EventHandler(this.saveAsToolStripMenuItem_Click);
            this.closeToolStripMenuItem.Text = "Close File";
            this.closeToolStripMenuItem.Click += new System.EventHandler(this.closeToolStripMenuItem_Click);
            this.detailsPanel.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.detailsPanel.Location = new System.Drawing.Point(12, 27);
            this.detailsPanel.Size = new System.Drawing.Size(1300, 722);
            this.chunkLabel.AutoSize = true;
            this.chunkLabel.Location = new System.Drawing.Point(13, 25);
            this.chunkLabel.Text = "Chunk";
            this.chunkComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            this.chunkComboBox.Location = new System.Drawing.Point(86, 22);
            this.chunkComboBox.Size = new System.Drawing.Size(333, 21);
            this.chunkComboBox.SelectedIndexChanged += new System.EventHandler(this.chunkComboBox_SelectedIndexChanged);
            this.chunkNameLabel.AutoSize = true;
            this.chunkNameLabel.Location = new System.Drawing.Point(438, 25);
            this.chunkNameLabel.Text = "Chunk Name";
            this.chunkNameTextBox.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            this.chunkNameTextBox.Location = new System.Drawing.Point(512, 22);
            this.chunkNameTextBox.Size = new System.Drawing.Size(782, 20);
            this.chunkNameTextBox.TextChanged += new System.EventHandler(this.chunkNameTextBox_TextChanged);
            this.chunkPathLabel.AutoSize = true;
            this.chunkPathLabel.Location = new System.Drawing.Point(13, 60);
            this.chunkPathLabel.Text = "Chunk Path";
            this.chunkPathTextBox.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            this.chunkPathTextBox.Location = new System.Drawing.Point(86, 57);
            this.chunkPathTextBox.Size = new System.Drawing.Size(1208, 20);
            this.chunkPathTextBox.TextChanged += new System.EventHandler(this.chunkPathTextBox_TextChanged);
            this.tabControl1.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.tabControl1.Location = new System.Drawing.Point(3, 89);
            this.tabControl1.Size = new System.Drawing.Size(1294, 630);
            this.tabControl1.Controls.Add(this.managersTabPage);
            this.tabControl1.Controls.Add(this.resourcesTabPage);
            this.tabControl1.Controls.Add(this.positionsTabPage);
            this.tabControl1.Controls.Add(this.forceFieldsTabPage);
            this.tabControl1.Controls.Add(this.mapIdsTabPage);
            this.tabControl1.Controls.Add(this.nodesTabPage);
            ConfigureListPage(this.managersTabPage, "Trail Setup", this.managersSplitContainer, this.managersListBox, this.managersButtonsPanel, this.managersPropertyGrid, this.addManagerButton, this.duplicateManagerButton, this.deleteManagerButton, this.AddManagerButton_Click, this.DuplicateManagerButton_Click, this.DeleteManagerButton_Click, 320);
            ConfigureListPage(this.resourcesTabPage, "Effects", this.resourcesSplitContainer, this.resourcesListBox, this.resourcesButtonsPanel, this.resourcesPropertyGrid, this.addResourceButton, this.duplicateResourceButton, this.deleteResourceButton, this.AddResourceButton_Click, this.DuplicateResourceButton_Click, this.DeleteResourceButton_Click, 320);
            ConfigureListPage(this.positionsTabPage, "Attachments", this.positionsSplitContainer, this.positionsListBox, this.positionsButtonsPanel, this.positionsPropertyGrid, this.addPositionButton, this.duplicatePositionButton, this.deletePositionButton, this.AddPositionButton_Click, this.DuplicatePositionButton_Click, this.DeletePositionButton_Click, 320);
            ConfigureListPage(this.forceFieldsTabPage, "Forces", this.forceFieldsSplitContainer, this.forceFieldsListBox, this.forceFieldsButtonsPanel, this.forceFieldsPropertyGrid, this.addForceFieldButton, this.duplicateForceFieldButton, this.deleteForceFieldButton, this.AddForceFieldButton_Click, this.DuplicateForceFieldButton_Click, this.DeleteForceFieldButton_Click, 320);
            ConfigureListPage(this.mapIdsTabPage, "Map IDs", this.mapIdsSplitContainer, this.mapIdsListBox, this.mapIdsButtonsPanel, this.mapIdsPropertyGrid, this.addMapButton, this.duplicateMapButton, this.deleteMapButton, this.AddMapButton_Click, this.DuplicateMapButton_Click, this.DeleteMapButton_Click, 360);
            ConfigureTimelinePage();
            this.detailsPanel.Controls.Add(this.tabControl1);
            this.detailsPanel.Controls.Add(this.chunkPathTextBox);
            this.detailsPanel.Controls.Add(this.chunkPathLabel);
            this.detailsPanel.Controls.Add(this.chunkNameTextBox);
            this.detailsPanel.Controls.Add(this.chunkNameLabel);
            this.detailsPanel.Controls.Add(this.chunkComboBox);
            this.detailsPanel.Controls.Add(this.chunkLabel);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1324, 761);
            this.Controls.Add(this.detailsPanel);
            this.Controls.Add(this.menuStrip1);
            this.MainMenuStrip = this.menuStrip1;
            this.MinimumSize = new System.Drawing.Size(1080, 700);
            this.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "Trail Chunk Editor";
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private void ConfigureListPage(TabPage page, string text, SplitContainer split, ListBox listBox, FlowLayoutPanel buttons, PropertyGrid grid, Button addButton, Button duplicateButton, Button deleteButton, System.EventHandler addHandler, System.EventHandler duplicateHandler, System.EventHandler deleteHandler, int splitterDistance)
        {
            page.Text = text;
            page.Padding = new Padding(3);
            page.UseVisualStyleBackColor = true;
            split.Dock = DockStyle.Fill;
            split.SplitterDistance = splitterDistance;
            listBox.Dock = DockStyle.Fill;
            listBox.IntegralHeight = false;
            listBox.FormattingEnabled = true;
            buttons.Dock = DockStyle.Bottom;
            buttons.Height = 36;
            addButton.Text = "Add";
            addButton.Width = 75;
            addButton.Click += addHandler;
            duplicateButton.Text = "Duplicate";
            duplicateButton.Width = 75;
            duplicateButton.Click += duplicateHandler;
            deleteButton.Text = "Delete";
            deleteButton.Width = 75;
            deleteButton.Click += deleteHandler;
            buttons.Controls.Add(addButton);
            buttons.Controls.Add(duplicateButton);
            buttons.Controls.Add(deleteButton);
            grid.Dock = DockStyle.Fill;
            grid.HelpVisible = false;
            grid.PropertySort = PropertySort.Categorized;
            split.Panel1.Controls.Add(listBox);
            split.Panel1.Controls.Add(buttons);
            split.Panel2.Controls.Add(grid);
            page.Controls.Add(split);
        }

        private void ConfigureTimelinePage()
        {
            this.nodesTabPage.Text = "Timelines";
            this.nodesTabPage.Padding = new Padding(3);
            this.nodesTabPage.UseVisualStyleBackColor = true;
            this.nodesSplitContainer.Dock = DockStyle.Fill;
            this.nodesSplitContainer.SplitterDistance = 320;
            this.nodeDetailsSplitContainer.Dock = DockStyle.Fill;
            this.nodeDetailsSplitContainer.Orientation = Orientation.Horizontal;
            this.nodeDetailsSplitContainer.SplitterDistance = 250;
            this.framesSplitContainer.Dock = DockStyle.Fill;
            this.framesSplitContainer.SplitterDistance = 320;
            this.nodesListBox.Dock = DockStyle.Fill;
            this.nodesListBox.IntegralHeight = false;
            this.nodesListBox.FormattingEnabled = true;
            this.framesListBox.Dock = DockStyle.Fill;
            this.framesListBox.IntegralHeight = false;
            this.framesListBox.FormattingEnabled = true;
            this.nodesButtonsPanel.Dock = DockStyle.Bottom;
            this.nodesButtonsPanel.Height = 36;
            this.framesButtonsPanel.Dock = DockStyle.Bottom;
            this.framesButtonsPanel.Height = 36;
            this.addNodeButton.Text = "Add";
            this.addNodeButton.Width = 75;
            this.addNodeButton.Click += new System.EventHandler(this.AddNodeButton_Click);
            this.duplicateNodeButton.Text = "Duplicate";
            this.duplicateNodeButton.Width = 75;
            this.duplicateNodeButton.Click += new System.EventHandler(this.DuplicateNodeButton_Click);
            this.deleteNodeButton.Text = "Delete";
            this.deleteNodeButton.Width = 75;
            this.deleteNodeButton.Click += new System.EventHandler(this.DeleteNodeButton_Click);
            this.nodesButtonsPanel.Controls.Add(this.addNodeButton);
            this.nodesButtonsPanel.Controls.Add(this.duplicateNodeButton);
            this.nodesButtonsPanel.Controls.Add(this.deleteNodeButton);
            this.addFrameButton.Text = "Add";
            this.addFrameButton.Width = 75;
            this.addFrameButton.Click += new System.EventHandler(this.AddFrameButton_Click);
            this.duplicateFrameButton.Text = "Duplicate";
            this.duplicateFrameButton.Width = 75;
            this.duplicateFrameButton.Click += new System.EventHandler(this.DuplicateFrameButton_Click);
            this.deleteFrameButton.Text = "Delete";
            this.deleteFrameButton.Width = 75;
            this.deleteFrameButton.Click += new System.EventHandler(this.DeleteFrameButton_Click);
            this.framesButtonsPanel.Controls.Add(this.addFrameButton);
            this.framesButtonsPanel.Controls.Add(this.duplicateFrameButton);
            this.framesButtonsPanel.Controls.Add(this.deleteFrameButton);
            this.nodeDetailsLabel.Dock = DockStyle.Top;
            this.nodeDetailsLabel.Height = 24;
            this.nodeDetailsLabel.Text = "Timeline Entry";
            this.frameDetailsLabel.Dock = DockStyle.Top;
            this.frameDetailsLabel.Height = 24;
            this.frameDetailsLabel.Text = "Frame Entry";
            this.nodesPropertyGrid.Dock = DockStyle.Fill;
            this.nodesPropertyGrid.HelpVisible = false;
            this.nodesPropertyGrid.PropertySort = PropertySort.Categorized;
            this.framesPropertyGrid.Dock = DockStyle.Fill;
            this.framesPropertyGrid.HelpVisible = false;
            this.framesPropertyGrid.PropertySort = PropertySort.Categorized;
            this.nodesSplitContainer.Panel1.Controls.Add(this.nodesListBox);
            this.nodesSplitContainer.Panel1.Controls.Add(this.nodesButtonsPanel);
            this.nodeDetailsSplitContainer.Panel1.Controls.Add(this.nodesPropertyGrid);
            this.nodeDetailsSplitContainer.Panel1.Controls.Add(this.nodeDetailsLabel);
            this.framesSplitContainer.Panel1.Controls.Add(this.framesListBox);
            this.framesSplitContainer.Panel1.Controls.Add(this.framesButtonsPanel);
            this.framesSplitContainer.Panel2.Controls.Add(this.framesPropertyGrid);
            this.framesSplitContainer.Panel2.Controls.Add(this.frameDetailsLabel);
            this.nodeDetailsSplitContainer.Panel2.Controls.Add(this.framesSplitContainer);
            this.nodesSplitContainer.Panel2.Controls.Add(this.nodeDetailsSplitContainer);
            this.nodesTabPage.Controls.Add(this.nodesSplitContainer);
        }
    }
}
